# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Migrate Cards

on:
  schedule:
    - cron: "30 2 * * 1"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install dependencies
      run: npm install
    - name: generate cards.js
      run: | 
        node ./index.js
        mv ./cards.js ../cards.js
    - name: switch branch to gh-pages
      run: git switch gh-pages -f
    - name: check for card definition changes
      run: |
        if cmp -s ../cards.js ./scripts/cards5.js;
        then
          echo "card definitions have not changed"
          echo "NEW_CARDS=false" >> "$GITHUB_ENV"
        else
          echo "card definitions have changed"
          echo "NEW_CARDS=true" >> "$GITHUB_ENV"
        fi
    - name: update card definitions, commit, and push changes
      if: env.NEW_CARDS == 'true'
      run: |
        mv ../cards.js ./scripts/cards5.js -f
        git config user.name bejbej
        git config user.email bejbej.uit@gmail.com
        git add ./scripts/cards5.js
        git commit -m "$(date +'%Y-%m-%d') automatic card definition update"
        git push

